import Head from 'next/head';
import { useState, useCallback, useMemo, useContext } from 'react';
import { AptosContext } from './_app';
import styles from '../styles/Home.module.css';

declare global {
  interface Window {
    aptos: any;
  }
}
export default function Aptos() {
  const [address, setAddress] = useState<string | null>(null);

  const aptosClient = useContext(AptosContext);

  const isAptosDefined = useMemo(
    () => (typeof window !== 'undefined' ? Boolean(window?.aptos) : false),
    []
  );

  const connectWallet = useCallback(async () => {
    try {
      if (isAptosDefined) {
        await window.aptos.connect();
        const account: { address: string } = await window.aptos.account();

        setAddress(account.address);
      }
    } catch (e) {
      console.error(e);
    }
  }, [isAptosDefined]);


  return (
    <div>
      <div className={styles.container}>
        <Head>
          <title>Aptos NFT Minting Sample Dapp</title>
          <meta name='description' content='Generated by create next app' />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <span>OpenMove</span>
          </h1>

          <div className={styles.connect}>
            <button
              className={styles.buttonConnect}
              disabled={!isAptosDefined || Boolean(address)}
              onClick={connectWallet}
            >
              <p> {!address ? 'Connect Wallet' : address}</p>
            </button>
          </div>
        </main>
      </div>
    </div>
  );
}
